// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Card: typeof import('./components/Card.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    HeroCard: typeof import('./components/HeroCard.vue')['default']
    HeroImage: typeof import('./components/HeroImage.vue')['default']
    HeroStats: typeof import('./components/HeroStats.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Selector: typeof import('./components/Selector.vue')['default']
    SimpleSelector: typeof import('./components/SimpleSelector.vue')['default']
    StatField: typeof import('./components/StatField.vue')['default']
  }
}
